---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.awsresources.com
  resources:
  - s3buckets
  - s3datas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.awsresources.com
  resources:
  - s3buckets/finalizers
  - s3datas/finalizers
  verbs:
  - update
- apiGroups:
  - storage.awsresources.com
  resources:
  - s3buckets/status
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - storage.awsresources.com
  resources:
  - s3datas/status
  verbs:
  - get
  - patch
  - update
